# ([(archivo, nlineascodigo)], [(archivo,nfunciones)], cant_archivos)
sa = (
    [
        ("Estado.cs", 187),
        ("Program.cs", 160),
        ("Alta.cs", 13),
    ],
    [
        ("Estado.cs", 37),
        ("Program.cs", 7),
        ("Alta.cs", 0),
    ],
    3,
)

cd = (
    [
        ("Cajero/Operaciones/Extraccion/Extraccion.cs", 92),
        ("Cajero/Operaciones/AltaUsuario/AltaUsuario.cs", 76),
        ("Cajero/Operaciones/ConsultaMovimientos/ConsultaMovimientos.cs", 74),
        ("Cajero/Operaciones/CambioClave/CambioClave.cs", 67),
        ("Cajero/Movimientos/Movimientos.cs", 63),
        ("Cajero/Programa.cs", 63),
        ("Cajero/Cajero/Cajero.cs", 59),
        ("Cajero/Estado.cs", 56),
        ("Cajero/Cajero/PoliticaSeguridad.cs", 50),
        ("Cajero/Usuarios/Usuarios.cs", 49),
        ("Cajero/Tipos/Importe.cs", 42),
        ("Cajero/Cajero/CajeroFactoria.cs", 40),
        ("Cajero/Dinero/GestionDinero.cs", 35),
        ("Cajero/HistorialCambiosClave/HistorialCambiosClave.cs", 34),
        ("Cajero/Operaciones/CargaCajero/CargaCajero.cs", 28),
        ("Cajero/Tipos/Documento.cs", 28),
        ("Cajero/Operaciones/ConsultaSaldo/ConsultaSaldo.cs", 27),
        ("Cajero/Operaciones/Operacion.cs", 25),
        ("Cajero/Parseadores/ParseadorParametrosAltaUsuario.cs", 24),
        ("Cajero/Parseadores/ParseadorParametrosConsultaMovimientos.cs", 24),
        ("Cajero/Estado/PersistenciaEstado.cs", 23),
        ("Cajero/Parseadores/ParseadorParametrosCambioClave.cs", 20),
        ("Cajero/Parseadores/ParseadorParametrosCargaCajero.cs", 20),
        ("Cajero/Parseadores/ParseadorParametrosExtraccion.cs", 20),
        ("Cajero/Parseadores/ParseadorParametrosConsultaSaldo.cs", 19),
        ("Cajero/Movimientos/Movimiento.cs", 14),
        ("Cajero/Movimientos/IMovimientos.cs", 13),
        ("Cajero/Usuarios/IUsuarios.cs", 11),
        ("Cajero/Operaciones/AltaUsuario/SolicitudAltaUsuario.cs", 11),
        ("Cajero/Usuarios/Usuario.cs", 11),
        ("Cajero/Operaciones/ConsultaMovimientos/SolicitudConsultaMovimientos.cs", 10),
        ("Cajero/Dinero/IGestionDinero.cs", 9),
        ("Cajero/HistorialCambiosClave/RegistroCambioClave.cs", 9),
        ("Cajero/Operaciones/AltaUsuario/ResultadoAltaUsuario.cs", 9),
        ("Cajero/Operaciones/ConsultaMovimientos/ResultadoConsultaMovimientos.cs", 9),
        ("Cajero/Movimientos/IEstadoMovimientos.cs", 8),
        ("Cajero/Operaciones/ConsultaSaldo/ResultadoConsultaSaldo.cs", 8),
        ("Cajero/Dinero/IEstadoDinero.cs", 7),
        ("Cajero/HistorialCambiosClave/IHistorialCambiosClave.cs", 7),
        ("Cajero/Estado/IPersistenciaEstado.cs", 7),
        ("Cajero/Usuarios/ResultadoAutenticarUsuario.cs", 7),
        ("Cajero/Operaciones/Extraccion/ResultadoExtraccion.cs", 7),
        ("Cajero/Operaciones/ResultadoOperacion.cs", 7),
        ("Cajero/Operaciones/CambioClave/SolicitudCambioClave.cs", 7),
        ("Cajero/Operaciones/CargaCajero/SolicitudCargaCajero.cs", 7),
        ("Cajero/Operaciones/Extraccion/SolicitudExtraccion.cs", 7),
        ("Cajero/HistorialCambiosClave/IEstadoHistorialCambiosClave.cs", 6),
        ("Cajero/Usuarios/IEstadoUsuarios.cs", 6),
        ("Cajero/Reloj/IReloj.cs", 6),
        ("Cajero/Reloj/Reloj.cs", 6),
        ("Cajero/Operaciones/ConsultaSaldo/SolicitudConsultaSaldo.cs", 6),
        ("Cajero/Cajero/PoliticaOperaciones.cs", 5),
        ("Cajero/Dinero/ResultadoValidarDisponibilidadDinero.cs", 5),
    ],
    [
        ("Cajero/Usuarios/Usuario.cs", 12),
        ("Cajero/Estado.cs", 11),
        ("Cajero/Tipos/Importe.cs", 11),
        ("Cajero/Cajero/Cajero.cs", 8),
        ("Cajero/Cajero/PoliticaSeguridad.cs", 8),
        ("Cajero/Usuarios/Usuarios.cs", 8),
        ("Cajero/Estado/PersistenciaEstado.cs", 7),
        ("Cajero/Tipos/Documento.cs", 6),
        ("Cajero/Operaciones/Extraccion/Extraccion.cs", 6),
        ("Cajero/Movimientos/Movimientos.cs", 6),
        ("Cajero/Operaciones/AltaUsuario/AltaUsuario.cs", 5),
        ("Cajero/Operaciones/CambioClave/CambioClave.cs", 4),
        ("Cajero/Operaciones/ConsultaMovimientos/ConsultaMovimientos.cs", 4),
        ("Cajero/Dinero/GestionDinero.cs", 4),
        ("Cajero/Cajero/CajeroFactoria.cs", 3),
        ("Cajero/HistorialCambiosClave/HistorialCambiosClave.cs", 3),
        ("Cajero/Operaciones/Operacion.cs", 3),
        ("Cajero/Operaciones/CargaCajero/CargaCajero.cs", 2),
        ("Cajero/Operaciones/ConsultaSaldo/ConsultaSaldo.cs", 2),
        ("Cajero/Parseadores/ParseadorParametrosAltaUsuario.cs", 1),
        ("Cajero/Parseadores/ParseadorParametrosCambioClave.cs", 1),
        ("Cajero/Parseadores/ParseadorParametrosCargaCajero.cs", 1),
        ("Cajero/Parseadores/ParseadorParametrosConsultaMovimientos.cs", 1),
        ("Cajero/Parseadores/ParseadorParametrosConsultaSaldo.cs", 1),
        ("Cajero/Parseadores/ParseadorParametrosExtraccion.cs", 1),
        ("Cajero/Programa.cs", 1),
        ("Cajero/Reloj/Reloj.cs", 1),
        ("Cajero/Dinero/IEstadoDinero.cs", 0),
        ("Cajero/HistorialCambiosClave/IEstadoHistorialCambiosClave.cs", 0),
        ("Cajero/Movimientos/IEstadoMovimientos.cs", 0),
        ("Cajero/Usuarios/IEstadoUsuarios.cs", 0),
        ("Cajero/Dinero/IGestionDinero.cs", 0),
        ("Cajero/HistorialCambiosClave/IHistorialCambiosClave.cs", 0),
        ("Cajero/Movimientos/IMovimientos.cs", 0),
        ("Cajero/Estado/IPersistenciaEstado.cs", 0),
        ("Cajero/Reloj/IReloj.cs", 0),
        ("Cajero/Usuarios/IUsuarios.cs", 0),
        ("Cajero/Movimientos/Movimiento.cs", 0),
        ("Cajero/Cajero/PoliticaOperaciones.cs", 0),
        ("Cajero/HistorialCambiosClave/RegistroCambioClave.cs", 0),
        ("Cajero/Operaciones/AltaUsuario/ResultadoAltaUsuario.cs", 0),
        ("Cajero/Usuarios/ResultadoAutenticarUsuario.cs", 0),
        ("Cajero/Operaciones/ConsultaMovimientos/ResultadoConsultaMovimientos.cs", 0),
        ("Cajero/Operaciones/ConsultaSaldo/ResultadoConsultaSaldo.cs", 0),
        ("Cajero/Operaciones/Extraccion/ResultadoExtraccion.cs", 0),
        ("Cajero/Operaciones/ResultadoOperacion.cs", 0),
        ("Cajero/Dinero/ResultadoValidarDisponibilidadDinero.cs", 0),
        ("Cajero/Operaciones/AltaUsuario/SolicitudAltaUsuario.cs", 0),
        ("Cajero/Operaciones/CambioClave/SolicitudCambioClave.cs", 0),
        ("Cajero/Operaciones/CargaCajero/SolicitudCargaCajero.cs", 0),
        ("Cajero/Operaciones/ConsultaMovimientos/SolicitudConsultaMovimientos.cs", 0),
        ("Cajero/Operaciones/ConsultaSaldo/SolicitudConsultaSaldo.cs", 0),
        ("Cajero/Operaciones/Extraccion/SolicitudExtraccion.cs", 0),
    ],
    58,
)
nd = (
    [
        ("cajero.js", 164),
        ("index.js", 32),
        ("estado.js", 30),
    ],
    [
        ("cajero.js", 12),
        ("estado.js", 3),
        ("index.js", 1),
    ],
    5,
)
fe = (
    [
        ("Programa.cs", 261),
        ("Estado.cs", 145),
    ],
    [
        ("Estado.cs", 33),
        ("Programa.cs", 1),
    ],
    3,
)
le = (
    [
        ("estado.py", 185),
        ("main.py", 110),
        ("datatypes.py", 41),
        ("utils.py", 5),
    ],
    [
        ("estado.py", 15),
        ("main.py", 7),
        ("datatypes.py", 4),
        ("utils.py", 2),
    ],
    5,
)
bf = (
    [
        ("cajero.py", 122),
        ("estado.py", 44),
        ("main.py", 36),
    ],
    [
        ("cajero.py", 7),
        ("estado.py", 3),
        ("main.py", 1),
    ],
    4,
)
df = (
    [
        ("main.py", 255),
        ("estado.py", 52),
    ],
    [
        ("main.py", 31),
        ("estado.py", 3),
    ],
    3,
)
gf = (
    [
        ("main.py", 228),
        ("estado.py", 56),
    ],
    [
        ("main.py", 30),
        ("estado.py", 3),
    ],
    3,
)
pg = (
    [
        ("operaciones/extraccion.js", 46),
        ("operaciones/cambio-clave.js", 45),
        ("estado.js", 44),
        ("index.js", 44),
        ("operaciones/alta.js", 41),
        ("operaciones/movimientos.js", 38),
        ("operaciones/carga.js", 12),
        ("operaciones/consulta-saldo.js", 11),
        ("utils.js", 11),
    ],
    [
        ("operaciones/movimientos.js", 5),
        ("operaciones/cambio-clave.js", 4),
        ("estado.js", 4),
        ("operaciones/extraccion.js", 4),
        ("utils.js", 4),
        ("operaciones/alta.js", 2),
        ("operaciones/consulta-saldo.js", 2),
        ("operaciones/carga.js", 1),
        ("index.js", 1),
    ],
    12,
)
wg = (
    [
        ("estado.py", 166),
        ("main.py", 48),
        ("exception.py", 20),
    ],
    [
        ("estado.py", 17),
        ("main.py", 1),
        ("exception.py", 0),
    ],
    4,
)
ij = (
    [
        ("Operaciones.cs", 307),
        ("Programa.cs", 216),
        ("Estado.cs", 86),
    ],
    [
        ("Estado.cs", 32),
        ("Operaciones.cs", 17),
        ("Programa.cs", 9),
    ],
    3,
)
mj = (
    [
        ("estado.py", 150),
        ("main.py", 38),
    ],
    [
        ("estado.py", 16),
        ("main.py", 3),
    ],
    3,
)
dl = (
    [
        ("main.py", 153),
        ("estado.py", 68),
    ],
    [
        ("estado.py", 4),
        ("main.py", 3),
    ],
    3,
)
fl = (
    [
        ("suboperaciones.js", 144),
        ("estado.js", 57),
        ("index.js", 33),
        ("constantes.js", 25),
        ("movimiento.js", 8),
    ],
    [
        ("suboperaciones.js", 15),
        ("estado.js", 4),
        ("index.js", 1),
        ("movimiento.js", 1),
        ("constantes.js", 0),
    ],
    7,
)
ml = (
    [
        ("main.py", 91),
        ("entidades/usuario.py", 85),
        ("estado.py", 39),
        ("operaciones/extraccion.py", 29),
        ("repositorios/usuarios.py", 27),
        ("operaciones/alta_usuario.py", 22),
        ("entidades/cajero.py", 18),
        ("args.py", 17),
        ("operaciones/actualizar_clave.py", 16),
        ("servicios/autenticacion.py", 15),
        ("operaciones/busqueda_movimientos.py", 15),
        ("operaciones/autorizadores/limite_diario.py", 12),
        ("operaciones/carga_cajero.py", 11),
        ("repositorios/cajeros.py", 10),
        ("operaciones/consulta_saldo.py", 9),
        ("operaciones/autorizadores/limit_monto.py", 8),
        ("operaciones/autorizadores/exito.py", 3),
    ],
    [
        ("entidades/usuario.py", 14),
        ("entidades/cajero.py", 5),
        ("repositorios/usuarios.py", 5),
        ("servicios/autenticacion.py", 3),
        ("estado.py", 3),
        ("operaciones/extraccion.py", 3),
        ("operaciones/actualizar_clave.py", 2),
        ("operaciones/alta_usuario.py", 2),
        ("args.py", 2),
        ("operaciones/busqueda_movimientos.py", 2),
        ("repositorios/cajeros.py", 2),
        ("operaciones/carga_cajero.py", 2),
        ("operaciones/consulta_saldo.py", 2),
        ("operaciones/autorizadores/limit_monto.py", 2),
        ("operaciones/autorizadores/limite_diario.py", 2),
        ("operaciones/autorizadores/exito.py", 1),
        ("main.py", 1),
    ],
    18,
)
vl = (
    [
        ("index.js", 215),
        ("estado.js", 36),
    ],
    [
        ("index.js", 6),
        ("estado.js", 3),
    ],
    4,
)
bm = (
    [
        ("estado.js", 58),
        ("operaciones/extraccion.js", 53),
        ("index.js", 42),
        ("operaciones/cambioClave.js", 39),
        ("operaciones/altaUsuario.js", 28),
        ("operaciones/carga.js", 22),
        ("operaciones/consultaMovimientos.js", 20),
        ("operaciones/consultaSaldo.js", 15),
        ("utils/isDatesMonthEqual.js", 7),
        ("utils/areDatesEqual.js", 6),
        ("errores/CambioDeClaveBloqueadoError.js", 6),
        ("errores/ClaveIncorrectaError.js", 6),
        ("errores/LimiteUsuariosAlcanzadoError.js", 6),
        ("errores/NoCumplePoliticaExtraccion2Error.js", 6),
        ("errores/NoCumplePoliticaExtraccionError.js", 6),
        ("errores/NoCumpleRequisitosClave1.js", 6),
        ("errores/NoCumpleRequisitosClave2.js", 6),
        ("errores/ParametrosInvalidosError.js", 6),
        ("errores/SaldoCajeroInsuficienteError.js", 6),
        ("errores/SaldoInsuficienteError.js", 6),
        ("errores/UsuarioInexistenteError.js", 6),
        ("errores/UsuarioNoHabilitadoError.js", 6),
        ("errores/UsuarioYaExistenteError.js", 6),
    ],
    [
        ("estado.js", 5),
        ("operaciones/extraccion.js", 3),
        ("operaciones/cambioClave.js", 2),
        ("operaciones/consultaMovimientos.js", 2),
        ("operaciones/altaUsuario.js", 1),
        ("utils/areDatesEqual.js", 1),
        ("errores/CambioDeClaveBloqueadoError.js", 1),
        ("operaciones/carga.js", 1),
        ("errores/ClaveIncorrectaError.js", 1),
        ("operaciones/consultaSaldo.js", 1),
        ("index.js", 1),
        ("utils/isDatesMonthEqual.js", 1),
        ("errores/LimiteUsuariosAlcanzadoError.js", 1),
        ("errores/NoCumplePoliticaExtraccion2Error.js", 1),
        ("errores/NoCumplePoliticaExtraccionError.js", 1),
        ("errores/NoCumpleRequisitosClave1.js", 1),
        ("errores/NoCumpleRequisitosClave2.js", 1),
        ("errores/ParametrosInvalidosError.js", 1),
        ("errores/SaldoCajeroInsuficienteError.js", 1),
        ("errores/SaldoInsuficienteError.js", 1),
        ("errores/UsuarioInexistenteError.js", 1),
        ("errores/UsuarioNoHabilitadoError.js", 1),
        ("errores/UsuarioYaExistenteError.js", 1),
    ],
    25,
)
bm2 = (
    [
        ("main.py", 181),
        ("estado.py", 74),
    ],
    [
        ("main.py", 14),
        ("estado.py", 4),
    ],
    3,
)
nm = (
    [
        ("index.js", 126),
        ("manager.js", 123),
        ("account/movementsAccount.js", 71),
        ("user/changePassword.js", 33),
        ("estado.js", 28),
        ("account/limitedWithdraw.js", 27),
        ("account/account.js", 26),
        ("atm.js", 22),
        ("user/user.js", 18),
        ("account/factory.js", 10),
        ("user/factory.js", 8),
        ("user/password.js", 3),
    ],
    [
        ("manager.js", 13),
        ("account/movementsAccount.js", 9),
        ("account/account.js", 6),
        ("account/limitedWithdraw.js", 6),
        ("atm.js", 4),
        ("index.js", 4),
        ("user/changePassword.js", 3),
        ("estado.js", 3),
        ("user/user.js", 3),
        ("account/factory.js", 1),
        ("user/factory.js", 1),
        ("user/password.js", 1),
    ],
    15,
)
pm = (
    [
        ("servicio.py", 77),
        ("estado.py", 62),
        ("operaciones.py", 45),
        ("main.py", 29),
        ("estado.json", 1),
    ],
    [
        ("servicio.py", 8),
        ("operaciones.py", 6),
        ("estado.py", 3),
        ("main.py", 1),
    ],
    5,
)
nn = (
    [
        ("main.py", 222),
        ("estado.py", 67),
        ("enums.py", 19),
        ("ext_func.py", 15),
        ("abst_types.py", 5),
        ("syn_types.py", 4),
    ],
    [
        ("main.py", 26),
        ("ext_func.py", 6),
        ("estado.py", 4),
        ("abst_types.py", 0),
        ("enums.py", 0),
        ("syn_types.py", 0),
    ],
    7,
)
dp = (
    [
        ("suboperaciones.js", 80),
        ("errores.js", 73),
        ("operaciones.js", 52),
        ("functions.js", 50),
        ("estado.js", 42),
        ("index.js", 40),
        ("enums.js", 19),
        ("globals.js", 6),
    ],
    [
        ("errores.js", 12),
        ("functions.js", 10),
        ("suboperaciones.js", 8),
        ("operaciones.js", 6),
        ("estado.js", 3),
        ("index.js", 1),
        ("enums.js", 0),
        ("globals.js", 0),
    ],
    10,
)
ms = (
    [
        ("estado.py", 49),
        ("extraccion.py", 41),
        ("main.py", 36),
        ("cambio_clave.py", 35),
        ("alta_usuario.py", 32),
        ("operacion.py", 32),
        ("movimientos.py", 30),
        ("auth.py", 22),
        ("carga_cajero.py", 13),
        ("command.py", 10),
        ("consulta_saldo.py", 8),
    ],
    [
        ("operacion.py", 8),
        ("alta_usuario.py", 6),
        ("cambio_clave.py", 5),
        ("extraccion.py", 5),
        ("movimientos.py", 4),
        ("auth.py", 3),
        ("carga_cajero.py", 3),
        ("estado.py", 3),
        ("command.py", 2),
        ("consulta_saldo.py", 2),
        ("main.py", 1),
    ],
    12,
)
ws = (
    [
        ("Programa.cs", 206),
        ("Estado.cs", 58),
        ("Usuario.cs", 15),
        ("Historico.cs", 12),
    ],
    [
        ("Programa.cs", 15),
        ("Estado.cs", 4),
        ("Usuario.cs", 2),
        ("Historico.cs", 0),
    ],
    4,
)
at = (
    [
        ("estado.js", 65),
        ("operaciones/extraccion.js", 45),
        ("index.js", 39),
        ("operaciones/movimientos.js", 38),
        ("operaciones/alta.js", 29),
        ("operaciones/clave.js", 26),
        ("operaciones/carga.js", 13),
        ("operaciones/saldo.js", 9),
        ("comunes/obtenerUsuario.js", 8),
        ("comunes/crearFecha.js", 4),
        ("comunes/validarClave.js", 4),
    ],
    [
        ("estado.js", 6),
        ("operaciones/movimientos.js", 5),
        ("operaciones/extraccion.js", 4),
        ("operaciones/alta.js", 3),
        ("operaciones/carga.js", 2),
        ("operaciones/clave.js", 2),
        ("comunes/obtenerUsuario.js", 2),
        ("comunes/crearFecha.js", 1),
        ("index.js", 1),
        ("operaciones/saldo.js", 1),
        ("comunes/validarClave.js", 1),
    ],
    14,
)
at2 = (
    [
        ("main.py", 132),
        ("estado.py", 65),
        ("estado.json", 1),
    ],
    [
        ("main.py", 4),
        ("estado.py", 3),
    ],
    3,
)
gt = (
    [
        ("Suboperaciones.cs", 97),
        ("Programa.cs", 85),
        ("Estado.cs", 68),
        ("FuncionesExternas.cs", 28),
        ("Tipos.cs", 25),
    ],
    [
        ("Estado.cs", 16),
        ("Suboperaciones.cs", 6),
        ("FuncionesExternas.cs", 5),
        ("Programa.cs", 1),
        ("Tipos.cs", 0),
    ],
    7,
)
bv = (
    [
        ("ops.py", 80),
        ("subops.py", 58),
        ("estado.py", 56),
        ("main.py", 52),
        ("enums.py", 47),
        ("movs.py", 30),
        ("tiempo.py", 15),
    ],
    [
        ("subops.py", 17),
        ("movs.py", 7),
        ("ops.py", 6),
        ("estado.py", 4),
        ("tiempo.py", 4),
        ("enums.py", 1),
        ("main.py", 1),
    ],
    8,
)
